apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels: { app: api }
  template:
    metadata:
      labels:
        app: api
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: api
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          ports: [{ name: http, containerPort: 8080 }]
          readinessProbe:
            httpGet: { path: /readyz, port: http }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /healthz, port: http }
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
          {{ toYaml .Values.api.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: referrals-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels: { app: worker }
  template:
    metadata:
      labels:
        app: worker
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: worker
      containers:
        - name: worker
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          resources:
          {{ toYaml .Values.worker.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: referrals-config
