apiVersion: v1
kind: ServiceAccount
metadata:
  name: api
  namespace: {{ .Release.Namespace }}
  annotations:
    azure.workload.identity/client-id: {{ required "api.clientId is required" .Values.api.clientId | quote }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker
  namespace: {{ .Release.Namespace }}
  annotations:
    azure.workload.identity/client-id: {{ required "worker.clientId is required" .Values.worker.clientId | quote }}
