name: terraform-apply-$(Date:yyyyMMdd).$(Rev:r)

trigger:
  branches:
    include:
      - main

pr: none

variables:
- group: AzureIDs
- name: terraformWorkingDirectory
  value: "infra/environments/dev"

pool:
  name: "Training-Batch-8.18"
  demands:
    - Agent.Name -equals Agent-Zein

stages:
  - stage: ApplyDev
    displayName: Apply Dev infrastructure
    jobs:
      - deployment: TerraformApply
        displayName: Approved Terraform apply
        environment: devz
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: AzureCLI@2
                  displayName: Terraform init and apply
                  inputs:
                    azureSubscription: $(azureServiceConnection)
                    scriptType: ps
                    scriptLocation: inlineScript
                    workingDirectory: $(terraformWorkingDirectory)
                    inlineScript: |
                      $env:TF_VAR_subscription_id = "$(subscriptionId)"
                      $env:TF_VAR_tenant_id = "$(tenantId)"
                      $env:TF_VAR_sql_admin_login = "$(sqlAdminLogin)"
                      $env:TF_VAR_sql_admin_password = "$(sqlAdminPassword)"
                      terraform init -input=false
                      terraform apply -input=false -auto-approve
